### ISSUE TITLE
Shift postgres & rabbitmq to docker internal network. 

### ISSUE THREAD

**Issue by 0x0elliot** [certego/BuffaLogs#19]
I don't like the fact that these services are exposed to the host machine. they should be only exposed to the internal docker network.

**Comment by 0x0elliot** [comment]
i just noticed that the docker configurations in general are pretty broken at the time. let me fix them in a separate PR first.

**Comment by ManofWax** [comment]
Yeah you are right: I've propose this fix #22 
We are going to merge it soon

**Comment by ManofWax** [comment]
We have merged the PR in develop branch. I'm closing this issue now, please reopen it if there are further issues.
