### ISSUE TITLE
Django authentication and user permission

### ISSUE THREAD

**Issue by ManofWax** [certego/BuffaLogs#2]
Django user authentication should be added to let user login.  

It should be keep it simple at the start, so basic django authentication will be enough and  two different users profiles are needed:

* normal users
* admins

**Comment by rezarex** [comment]
Hi, I am new to open source. May I work on this?

**Comment by ManofWax** [comment]
Yes, you could start by implementing simple using authentication as described in official [django docs](https://docs.djangoproject.com/en/4.1/topics/auth/). The difference between `admin` and `users` should be the `admin` could also access django admin interface.

**Comment by YogeeshH-k** [comment]
@ManofWax Hi, if this issue is still available can I give it a shot?

**Comment by ManofWax** [comment]
Yes, rezarex PR looks like is stalled

**Comment by VidyaYadavv1519** [comment]
hi if this issue is still available

**Comment by ManofWax** [comment]
No, I'm closing the issue. It is already implemented we are going to release soon
